
export const GAME_DATA_1 = [
  // Level 1-2 items (Primary provided list)
  { char: '昼', pinyin: 'zhòu' }, { char: '耘', pinyin: 'yún' }, { char: '供', pinyin: 'gòng' },
  { char: '稚', pinyin: 'zhì' }, { char: '漪', pinyin: 'yī' }, { char: '昨', pinyin: 'zhà' },
  { char: '啃', pinyin: 'kěn' }, { char: '樱', pinyin: 'yīng' }, { char: '蚌', pinyin: 'bàng' },
  { char: '割', pinyin: 'gē' }, { char: '嘟', pinyin: 'dū' }, { char: '倭', pinyin: 'wō' },
  { char: '拴', pinyin: 'shuān' }, { char: '啰', pinyin: 'luo' }, { char: '逛', pinyin: 'guàng' },
  { char: '排', pinyin: 'pái' }, { char: '徊', pinyin: 'huái' }, { char: '渺', pinyin: 'miǎo' },
  { char: '篝', pinyin: 'gōu' }, { char: '萌', pinyin: 'méng' }, { char: '澄', pinyin: 'chéng' },
  { char: '澈', pinyin: 'chè' }, { char: '旖', pinyin: 'yǐ' }, { char: '旎', pinyin: 'nǐ' },
  { char: '瑞', pinyin: 'ruì' }, { char: '莱', pinyin: 'lái' }, { char: '垠', pinyin: 'yín' },
  { char: '顷', pinyin: 'qǐng' }, { char: '峨', pinyin: 'é' }, { char: '燕', pinyin: 'yān' },
  { char: '缀', pinyin: 'zhuì' }, { char: '腮', pinyin: 'sāi' }, { char: '虬', pinyin: 'qiú' },
  { char: '玷', pinyin: 'diàn' }, { char: '郑', pinyin: 'zhèng' }, { char: '秉', pinyin: 'bǐng' },
  { char: '飕', pinyin: 'sōu' }, { char: '玛', pinyin: 'mǎ' }, { char: '撩', pinyin: 'liāo' },
  { char: '绢', pinyin: 'juàn' }, { char: '侨', pinyin: 'qiáo' }, { char: '眷', pinyin: 'juàn' },
  
  // Level 3-4 items (Additional from prompt)
  { char: '妒', pinyin: 'dù' }, { char: '忌', pinyin: 'jì' }, { char: '曹', pinyin: 'cáo' },
  { char: '督', pinyin: 'dū' }, { char: '委', pinyin: 'wěi' }, { char: '鲁', pinyin: 'lǔ' },
  { char: '遮', pinyin: 'zhē' }, { char: '疑', pinyin: 'yí' }, { char: '惑', pinyin: 'huò' },
  { char: '寨', pinyin: 'zhài' }, { char: '擂', pinyin: 'lèi' }, { char: '呐', pinyin: 'nà' },
  { char: '插', pinyin: 'chā' }, { char: '冈', pinyin: 'gāng' }, { char: '饥', pinyin: 'jī' },
  { char: '碟', pinyin: 'dié' }, { char: '斤', pinyin: 'jīn' }, { char: '俺', pinyin: 'ǎn' },
  { char: '榜', pinyin: 'bǎng' }, { char: '杖', pinyin: 'zhàng' }, { char: '申', pinyin: 'shēn' },
  { char: '兼', pinyin: 'jiān' }, { char: '勿', pinyin: 'wù' }, { char: '拖', pinyin: 'tuō' },
  { char: '悉', pinyin: 'xī' }, { char: '坠', pinyin: 'zhuì' }, { char: '膛', pinyin: 'táng' },
  { char: '截', pinyin: 'jié' }, { char: '篱', pinyin: 'lí' }, { char: '仞', pinyin: 'rèn' },
  { char: '岳', pinyin: 'yuè' }, { char: '摩', pinyin: 'mó' }, { char: '遗', pinyin: 'yí' },
  { char: '涕', pinyin: 'tì' }, { char: '巫', pinyin: 'wū' },

  // Levels 5-10 expanded (Common 5th grade vocab)
  { char: '跤', pinyin: 'jiāo' }, { char: '腕', pinyin: 'wàn' }, { char: '搂', pinyin: 'lǒu' },
  { char: '绽', pinyin: 'zhàn' }, { char: '咕', pinyin: 'gū' }, { char: '姆', pinyin: 'mǔ' },
  { char: '翘', pinyin: 'qiào' }, { char: '惩', pinyin: 'chéng' }, { char: '监', pinyin: 'jiān' },
  { char: '矛', pinyin: 'máo' }, { char: '盾', pinyin: 'dùn' }, { char: '誉', pinyin: 'yù' },
  { char: '吾', pinyin: 'wú' }, { char: '履', pinyin: 'lǚ' }, { char: '刺', pinyin: 'cì' },
  { char: '匪', pinyin: 'fěi' }, { char: '绷', pinyin: 'běng' }, { char: '审', pinyin: 'shěn' },
  { char: '剂', pinyin: 'jì' }, { char: '施', pinyin: 'shī' }, { char: '吭', pinyin: 'kēng' },
  { char: '衷', pinyin: 'zhōng' }, { char: '慈', pinyin: 'cí' }, { char: '祥', pinyin: 'xiáng' },
  { char: '瑞', pinyin: 'ruì' }, { char: '芝', pinyin: 'zhī' }, { char: '玛', pinyin: 'mǎ' },
  { char: '埃', pinyin: 'āi' }, { char: '及', pinyin: 'jí' }, { char: '尼', pinyin: 'ní' },
  { char: '罗', pinyin: 'luó' }, { char: '河', pinyin: 'hé' }, { char: '象', pinyin: 'xiàng' },
  { char: '尊', pinyin: 'zūn' }, { char: '严', pinyin: 'yán' }, { char: '艇', pinyin: 'tǐng' },
  { char: '舱', pinyin: 'cāng' }, { char: '翘', pinyin: 'qiào' }, { char: '祷', pinyin: 'dǎo' },
  { char: '雇', pinyin: 'gù' }, { char: '哗', pinyin: 'huá' }, { char: '码', pinyin: 'mǎ' },
  { char: '笼', pinyin: 'lóng' }, { char: '吆', pinyin: 'yāo' }, { char: '喝', pinyin: 'hè' },
  { char: '铃', pinyin: 'líng' }, { char: '铛', pinyin: 'dāng' }, { char: '罐', pinyin: 'guàn' },
  { char: '恢', pinyin: 'huī' }, { char: '复', pinyin: 'fù' }, { char: '畜', pinyin: 'chù' },
  { char: '牲', pinyin: 'shēng' }, { char: '仪', pinyin: 'yí' }, { char: '眺', pinyin: 'tiào' },
  { char: '骏', pinyin: 'jùn' }, { char: '膘', pinyin: 'biāo' }, { char: '驰', pinyin: 'chí' },
  { char: '辽', pinyin: 'liáo' }, { char: '阔', pinyin: 'kuò' }, { char: '绵', pinyin: 'mián' },
  { char: '凳', pinyin: 'dèng' }, { char: '吆', pinyin: 'yāo' }, { char: '铃', pinyin: 'líng' },
  { char: '阻', pinyin: 'zǔ' }, { char: '隔', pinyin: 'gé' }, { char: '痴', pinyin: 'chī' },
  { char: '愧', pinyin: 'kuì' }, { char: '幸', pinyin: 'xìng' }, { char: '亏', pinyin: 'kuī' },
  { char: '澄', pinyin: 'chéng' }, { char: '澈', pinyin: 'chè' }, { char: '赋', pinyin: 'fù' },
  { char: '胚', pinyin: 'pēi' }, { char: '胎', pinyin: 'tāi' }, { char: '祸', pinyin: 'huò' },
  { char: '患', pinyin: 'huàn' }, { char: '滑', pinyin: 'huá' }, { char: '稽', pinyin: 'jī' },
  { char: '窘', pinyin: 'jiǒng' }, { char: '迫', pinyin: 'pò' }, { char: '绞', pinyin: 'jiǎo' },
  { char: '尽', pinyin: 'jǐn' }, { char: '脑', pinyin: 'nǎo' }, { char: '汁', pinyin: 'zhī' },
  { char: '梁', pinyin: 'liáng' }, { char: '诣', pinyin: 'yì' }, { char: '禽', pinyin: 'qín' },
  { char: '瘙', pinyin: 'sào' }, { char: '痒', pinyin: 'yǎng' }, { char: '秽', pinyin: 'huì' },
  { char: '轧', pinyin: 'yà' }, { char: '拧', pinyin: 'níng' }, { char: '螺', pinyin: 'luó' },
  { char: '纽', pinyin: 'niǔ' }, { char: '扣', pinyin: 'kòu' }, { char: '貌', pinyin: 'mào' },
  { char: '仓', pinyin: 'cāng' }, { char: '库', pinyin: 'kù' }, { char: '斯', pinyin: 'sī' },
  { char: '严', pinyin: 'yán' }, { char: '厉', pinyin: 'lì' }, { char: '庸', pinyin: 'yōng' },
  { char: '俗', pinyin: 'sú' }, { char: '考', pinyin: 'kǎo' }, { char: '证', pinyin: 'zhèng' },
  { char: '诸', pinyin: 'zhū' }, { char: '葛', pinyin: 'gě' }, { char: '亮', pinyin: 'liàng' },
  { char: '周', pinyin: 'zhōu' }, { char: '瑜', pinyin: 'yú' }, { char: '曹', pinyin: 'cáo' },
  { char: '操', pinyin: 'cāo' }, { char: '武', pinyin: 'wǔ' }, { char: '松', pinyin: 'sōng' },
  { char: '鹤', pinyin: 'hè' }, { char: '厦', pinyin: 'shà' }, { char: '廊', pinyin: 'láng' },
  { char: '漆', pinyin: 'qī' }, { char: '栏', pinyin: 'lán' }, { char: '柱', pinyin: 'zhù' },
  { char: '昆', pinyin: 'kūn' }, { char: '仑', pinyin: 'lún' }, { char: '耸', pinyin: 'sǒng' },
  { char: '嵌', pinyin: 'qiàn' }, { char: '螺', pinyin: 'luó' }, { char: '甸', pinyin: 'diàn' },
  { char: '瓣', pinyin: 'bàn' }, { char: '蕊', pinyin: 'ruǐ' }, { char: '芬', pinyin: 'fēn' },
  { char: '芳', pinyin: 'fāng' }, { char: '泌', pinyin: 'mì' }, { char: '沁', pinyin: 'qìn' },
  { char: '肺', pinyin: 'fèi' }, { char: '腑', pinyin: 'fǔ' }, { char: '吭', pinyin: 'háng' },
  { char: '哧', pinyin: 'chī' }, { char: '蹬', pinyin: 'dēng' }, { char: '咔', pinyin: 'kǎ' },
  { char: '嚓', pinyin: 'chā' }, { char: '嗖', pinyin: 'sōu' }, { char: '嗖', pinyin: 'sōu' },
  { char: '哐', pinyin: 'kuāng' }, { char: '啷', pinyin: 'lāng' }, { char: '咔', pinyin: 'kǎ' },
  { char: '嚓', pinyin: 'chā' }, { char: '咕', pinyin: 'gū' }, { char: '噜', pinyin: 'lū' }
];

export const GAME_DATA_2 = [
  { correct: "拔", wrong: "拨", pinyin: "bá" },
  { correct: "昼", wrong: "旦", pinyin: "zhòu" },
  { correct: "耘", wrong: "运", pinyin: "yún" },
  { correct: "桑", wrong: "嗓", pinyin: "sāng" },
  { correct: "晓", wrong: "饶", pinyin: "xiǎo" },
  { correct: "蝴", wrong: "胡", pinyin: "hú" },
  { correct: "蝶", wrong: "喋", pinyin: "dié" },
  { correct: "蜻", wrong: "晴", pinyin: "qīng" },
  { correct: "蜓", wrong: "挺", pinyin: "tíng" },
  { correct: "蚂", wrong: "吗", pinyin: "mǎ" },
  { correct: "蚱", wrong: "炸", pinyin: "zhà" },
  { correct: "樱", wrong: "婴", pinyin: "yīng" },
  { correct: "榆", wrong: "愉", pinyin: "yú" },
  { correct: "瞎", wrong: "割", pinyin: "xiā" },
  { correct: "铲", wrong: "产", pinyin: "chǎn" },
  { correct: "锄", wrong: "助", pinyin: "chú" },
  { correct: "割", wrong: "宪", pinyin: "gē" },
  { correct: "承", wrong: "成", pinyin: "chéng" },
  { correct: "拴", wrong: "全", pinyin: "shuān" },
  { correct: "瓢", wrong: "飘", pinyin: "piáo" },
  { correct: "逛", wrong: "狂", pinyin: "guàng" },
  { correct: "妒", wrong: "户", pinyin: "dù" },
  { correct: "忌", wrong: "已", pinyin: "jì" },
  { correct: "曹", wrong: "槽", pinyin: "cáo" },
  { correct: "督", wrong: "叔", pinyin: "dū" },
  { correct: "委", wrong: "季", pinyin: "wěi" },
  { correct: "鲁", wrong: "鱼", pinyin: "lǔ" },
  { correct: "遮", wrong: "庶", pinyin: "zhē" },
  { correct: "疑", wrong: "凝", pinyin: "yí" },
  { correct: "惑", wrong: "或", pinyin: "huò" },
  { correct: "寨", wrong: "塞", pinyin: "zhài" },
  { correct: "擂", wrong: "雷", pinyin: "lèi" },
  { correct: "呐", wrong: "内", pinyin: "nà" },
  { correct: "插", wrong: "干", pinyin: "chā" },
  { correct: "冈", wrong: "网", pinyin: "gāng" },
  { correct: "饥", wrong: "机", pinyin: "jī" },
  { correct: "碟", wrong: "蝶", pinyin: "dié" },
  { correct: "俺", wrong: "奄", pinyin: "ǎn" },
  { correct: "榜", wrong: "傍", pinyin: "bǎng" },
  { correct: "杖", wrong: "仗", pinyin: "zhàng" }
];

export const GAME_DATA_3 = [
  { question: "蝴蝶", blankIndex: 1, answer: "蝶", options: ["蝶", "喋", "叶", "叠"] },
  { question: "蜻蜓", blankIndex: 0, answer: "蜻", options: ["蜻", "请", "清", "青"] },
  { question: "蚂蚱", blankIndex: 1, answer: "蚱", options: ["蚱", "炸", "榨", "作"] },
  { question: "圆滚滚", blankIndex: 1, answer: "滚", options: ["滚", "波", "混", "衮"] },
  { question: "明晃晃", blankIndex: 2, answer: "晃", options: ["晃", "光", "洗", "先"] },
  { question: "樱桃", blankIndex: 0, answer: "樱", options: ["樱", "婴", "鹦", "映"] },
  { question: "榆树", blankIndex: 0, answer: "榆", options: ["榆", "愉", "喻", "渝"] },
  { question: "瞎闹", blankIndex: 0, answer: "瞎", options: ["瞎", "害", "割", "合"] },
  { question: "锄头", blankIndex: 0, answer: "锄", options: ["锄", "助", "粗", "初"] },
  { question: "承认", blankIndex: 0, answer: "承", options: ["承", "成", "诚", "呈"] },
  { question: "随意", blankIndex: 0, answer: "随", options: ["随", "腿", "隧", "隋"] },
  { question: "妒忌", blankIndex: 0, answer: "妒", options: ["妒", "户", "护", "炉"] },
  { question: "委托", blankIndex: 0, answer: "委", options: ["委", "季", "魏", "微"] },
  { question: "预计", blankIndex: 0, answer: "预", options: ["预", "余", "雨", "渔"] },
  { question: "紧急", blankIndex: 1, answer: "急", options: ["急", "及", "忌", "极"] },
  { question: "军令状", blankIndex: 2, answer: "状", options: ["状", "壮", "庄", "撞"] },
  { question: "探听", blankIndex: 0, answer: "探", options: ["探", "深", "谈", "贪"] },
  { question: "疑惑", blankIndex: 1, answer: "惑", options: ["惑", "或", "活", "话"] },
  { question: "私自", blankIndex: 0, answer: "私", options: ["私", "司", "和", "似"] },
  { question: "调度", blankIndex: 0, answer: "调", options: ["调", "钓", "周", "刁"] },
  { question: "神机妙算", blankIndex: 3, answer: "算", options: ["算", "随", "颂", "送"] },
  { question: "拟定", blankIndex: 0, answer: "拟", options: ["拟", "似", "以", "从"] },
  { question: "损失", blankIndex: 0, answer: "损", options: ["损", "员", "勋", "润"] },
  { question: "情不自禁", blankIndex: 3, answer: "禁", options: ["禁", "经", "京", "进"] },
  { question: "参谋", blankIndex: 1, answer: "谋", options: ["谋", "某", "煤", "没"] }
];
